### ISSUE TITLE
Throws "terminate called after throwing an instance of 'std::out_of_range"  translating MIPSEL opcode

### ISSUE THREAD

**Issue by kye4u2** [angr/pypcode#15]
Language: MIPS:LE:32:default

opcode = b"\x40\x00\x40\x10"
result = context.translate(opcode, 0)

Yields the following error: "terminate called after throwing an instance of 'std::out_of_range'
  what():  Attempting to lift outside buffer range"

In ghidra, this is what you get:

        00405304 04 00 40 10     beq        v0,zero,LAB_00405318
                                                      $U240:1 = INT_EQUAL v0, 0:4
                                                      at = INT_OR at, 0:4
                                                      CBRANCH *[ram]0x405318:4, $U240

**Comment by nabar33** [comment]
Hi, I recently was working with MIPS stuff and the reason this is happening is the MIPS sleigh specs do a look ahead when translating branch instructions. They inline the delay slot instruction's pcode into the branch's pcode translation.

It's throwing std::out_of_range because it's expecting there to be another 4 bytes for the delay slot instruction.

Hope this help some!

**Comment by kye4u2** [comment]
oh... Thanks for sharing that.  This is definitely helpful!!!.
